### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by mdml** [lrgr/mutation-signature-explorer#68]
I do not know why, but this URL does not work for me:

> https://imuse.lrgr.io/#{%22datasets%22:[%22PCAWG-BLCA-US%22,%22PCAWG-LIRI-JP%22,%22PCAWG-LINC-JP%22,%22PCAWG-LIHC-US%22,%22PCAWG-LICA-FR%22],%22signatures%22:[%22SBS19%22,%22SBS1%22,%22SBS4%22,%22SBS5%22,%22SBS6%22,%22SBS9%22,%22SBS12%22,%22SBS14%22,%22SBS16%22,%22SBS17a%22,%22SBS17b%22,%22SBS18%22,%22SBS3%22,%22SBS22%22,%22SBS23%22,%22SBS24%22,%22SBS26%22,%22SBS28%22,%22SBS29%22,%22SBS30%22,%22SBS31%22,%22SBS35%22,%22SBS37%22,%22SBS40%22],%22plots%22:[],%22chr%22:{%22name%22:%22*%22,%22start%22:0,%22end%22:0},%22mode%22:{%22mode%22:%22overview%22,%22title%22:%22Overview%22,%22options%22:{}}}

**Comment by keller-mark** [comment]
This is the timeout issue. I will take off the "overview" manhattan plot for now and put it on the single donor page https://github.com/lrgr/mutation-signature-explorer/issues/56
